=== PRDMonash/gpcML/Test_XML_Files/gpcML.xsd
<?xml version="1.1" encoding="UTF-8"?>
<!-- edited with XMLSpy v2026 (x64) (https://www.altova.com) by Oliver (Monash) -->
<!-- W3C Schema generated by XMLSpy v2026 (x64) (https://www.altova.com) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:dx="https://www.polymatter.net/software" xmlns:xmime="http://www.w3.org/2005/05/xmlmime">
	<xs:element name="gpcML" type="gpcMLType">
		<xs:annotation>
			<xs:documentation>Root element of the XSD</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:complexType name="gpcMLType">
		<xs:annotation>
			<xs:documentation>
			This is the data type definition which defines the allowed elements/attributes inside of the nmrML xsd.
			</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="ContactList" type="ContactListType"/>
			<xs:element name="Metadata" type="MetadataType"/>
			<xs:element name="InstrumentInfoList" type="InstrumentListType" minOccurs="0"/>
			<xs:element name="RunTimeData" type="RuntimeDataType"/>
			<xs:element name="CalibrationData" type="CalibrationDataType"/>
		</xs:sequence>
		<xs:attribute name="Version" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>gpcML version used.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="id" type="xs:int">
			<xs:annotation>
				<xs:documentation>id associated with the gpcML document</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="Sample">
		<xs:attribute name="Name" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="SampleType"/>
	<xs:complexType name="EluGramType"/>
	<xs:complexType name="MetadataListType">
		<xs:annotation>
			<xs:documentation>contains a sequence of metadata associated with the data</xs:documentation>
		</xs:annotation>
	</xs:complexType>
	<xs:complexType name="ContactType">
		<xs:annotation>
			<xs:documentation>contact information to link data to a laborotory/analyst</xs:documentation>
		</xs:annotation>
		<xs:attribute name="FirstName" type="xs:string" use="required"/>
		<xs:attribute name="MiddleName" type="xs:string" use="optional"/>
		<xs:attribute name="LastName" type="xs:string" use="required"/>
		<xs:attribute name="E-mail" type="xs:string" use="required"/>
		<xs:attribute name="Institution" type="xs:string" use="optional"/>
	</xs:complexType>
	<xs:complexType name="ContactListType">
		<xs:sequence>
			<xs:element name="Contact" type="ContactType" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="InstrumentListType">
		<xs:annotation>
			<xs:documentation>A complexType to contain all necessary instruments used to produce the experimental data</xs:documentation>
		</xs:annotation>
		<xs:choice maxOccurs="unbounded">
			<xs:element name="RIDetectorInfo" type="RIDetectorInfoType"/>
			<xs:element name="UVvisInfo" type="UVvisInfoType" minOccurs="0"/>
			<xs:element name="LightScatteringInfo" type="LightScatteringInfoType" minOccurs="0"/>
			<xs:element name="ViscometerInfo" type="ViscometerInfoType" minOccurs="0"/>
			<xs:element name="ColumnInfo" type="ColumnInfoListType"/>
		</xs:choice>
	</xs:complexType>
	<xs:complexType name="InstrumentInfoType">
		<xs:annotation>
			<xs:documentation>Specific information relating to the equipment to allow easy lookup of the parts</xs:documentation>
		</xs:annotation>
		<xs:attribute name="Name" type="xs:string" use="optional"/>
		<xs:attribute name="SerialNumber" type="xs:int" use="required"/>
		<xs:attribute name="Manufacturer" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="RuntimeDataType">
		<xs:annotation>
			<xs:documentation>Contains a list of: the elugram data in a binary heap, List of intergration volumes (if multiple intergrations exist), system peak and internal standard peak volumes</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="InstrumentConfiguration" type="InstrumentConfigurationType"/>
			<xs:element name="RawData" type="RawDataType">
				<xs:annotation>
					<xs:documentation>Stored as a base64 encoded data</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="IntergrationValues" type="IntergrationValuesListType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="CalibrationType"/>
	<xs:complexType name="MetadataType">
		<xs:attribute name="date" type="xs:date" use="required"/>
		<xs:attribute name="MethodName" type="xs:string" use="required"/>
		<xs:attribute name="CalibrationName" type="xs:string" use="optional"/>
		<xs:attribute name="Operator" type="xs:string" use="required"/>
		<xs:attribute name="InstrumentName" type="xs:string" use="required"/>
		<xs:attribute name="RunTime" type="xs:time" use="optional"/>
		<xs:attribute name="lastServiceDate" type="xs:date" use="optional"/>
		<xs:attribute name="PolymerName" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="RIDetectorInfoType">
		<xs:sequence>
			<xs:element name="IDinfo" type="InstrumentInfoType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ViscometerInfoType">
		<xs:sequence>
			<xs:element name="IDinfo" type="InstrumentInfoType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="UVvisInfoType">
		<xs:sequence>
			<xs:element name="IDinfo" type="InstrumentInfoType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="RIDetectorRunType"/>
	<xs:complexType name="ViscometerRunType"/>
	<xs:complexType name="UVvisRunType"/>
	<xs:complexType name="LightScatteringInfoType">
		<xs:sequence>
			<xs:element name="IDinfo" type="InstrumentInfoType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="LightScatteringRunType"/>
	<xs:complexType name="InstrumentConfigurationType">
		<xs:sequence>
			<xs:element name="ColumnList" type="ColumnListConfigurationType">
				<xs:annotation>
					<xs:documentation>Columns stored in the order the sample runs through, column at the top of the list will be the column which separates the sample first</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="OvenList" type="OvenListType"/>
			<xs:element name="Pump" type="PumpConfigurationType"/>
			<xs:element name="Injector" type="InjectorConfigurationType" minOccurs="0"/>
			<xs:element name="Eluent" type="EluentType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="RawDataType">
		<xs:simpleContent>
			<xs:extension base="xs:base64Binary">
				<xs:attribute name="Compression" type="xs:boolean" use="required"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="OvenListType">
		<xs:choice maxOccurs="2">
			<xs:element name="ColumnOven" type="OvenConfigurationType"/>
			<xs:element name="gpcOven" type="OvenConfigurationType"/>
		</xs:choice>
	</xs:complexType>
	<xs:complexType name="UVvisConfigurationType"/>
	<xs:complexType name="ColumnInfoType">
		<xs:attribute name="DateOfInstallation" type="xs:date" use="optional"/>
		<xs:attribute name="PlateCount" type="xs:int" use="optional"/>
	</xs:complexType>
	<xs:complexType name="ColumnInfoListType">
		<xs:sequence>
			<xs:element name="IDinfo" type="InstrumentInfoType"/>
			<xs:element name="Column" type="ColumnInfoType" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="RIDetectorConfigurationType"/>
	<xs:complexType name="LightScatteringConfigurationType"/>
	<xs:complexType name="ColumnListConfigurationType">
		<xs:sequence>
			<xs:element name="GuardColumn" type="ColumnConfigurationType" minOccurs="0"/>
			<xs:element name="Column" type="ColumnConfigurationType" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="PumpConfigurationType">
		<xs:attribute name="FlowRate" type="PositiveFloatType" use="required"/>
	</xs:complexType>
	<xs:complexType name="InjectorConfigurationType">
		<xs:attribute name="InjectionVolume" type="PositiveFloatType" use="required"/>
	</xs:complexType>
	<xs:complexType name="OvenConfigurationType">
		<xs:attribute name="Temperature" type="xs:int" use="required"/>
	</xs:complexType>
	<xs:complexType name="ColumnConfigurationType">
		<xs:attribute name="PoreSizeMin" type="xs:positiveInteger" use="required"/>
		<xs:attribute name="PoreSizeMax" type="xs:positiveInteger" use="required"/>
		<xs:attribute name="StationaryPhase" type="xs:string" use="optional"/>
		<xs:attribute name="DateOfInstallation" type="xs:date" use="optional"/>
	</xs:complexType>
	<xs:complexType name="GuardColumnConfigurationType"/>
	<xs:complexType name="CalibrationDataType">
		<xs:sequence>
			<xs:element name="TypeOfFit" type="DegreePolyType">
				<xs:annotation>
					<xs:documentation>Stores the degree of polynomial. used to affirm the correct number of coeffs are added.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="CoeffList" type="CoeffListType"/>
		</xs:sequence>
		<xs:assert test="
			TypeOfFit + 1 = count(
				CoeffList/*[
					self::QuinticCoeff or 
					self::QuarticCoeff or 
					self::CubicCoeff or 
					self::QuadraticCoeff or 
					self::LinearCoeff or 
					self::constant
				])
		"/>
	</xs:complexType>
	<xs:complexType name="PolyCoeffType"/>
	<xs:complexType name="StandardUsedType"/>
	<xs:complexType name="RangeOfStandardsType"/>
	<xs:complexType name="CalibrationDateType"/>
	<xs:simpleType name="DegreePolyType">
		<xs:annotation>
			<xs:documentation>defines if it is a 3rd, 4th or 5th order polynomial</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:int">
			<xs:minInclusive value="3"/>
			<xs:maxInclusive value="5"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="CoeffListType">
		<xs:sequence>
			<xs:element name="QuinticCoeff" type="CoeffType" minOccurs="0"/>
			<xs:element name="QuarticCoeff" type="CoeffType" minOccurs="0"/>
			<xs:element name="CubicCoeff" type="CoeffType"/>
			<xs:element name="QuadraticCoeff" type="CoeffType"/>
			<xs:element name="LinearCoeff" type="CoeffType"/>
			<xs:element name="constant" type="CoeffType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="CoeffType">
		<xs:restriction base="xs:float"/>
	</xs:simpleType>
	<xs:complexType name="EluentType">
		<xs:sequence>
			<xs:element name="SolventName" type="xs:string"/>
			<xs:element name="AdditiveName" type="xs:string" minOccurs="0"/>
			<xs:element name="RecyclingMode" type="xs:boolean"/>
			<xs:choice minOccurs="1" maxOccurs="2">
				<xs:element name="Ratio" type="RatioType">
					<xs:annotation>
						<xs:documentation>Ratio between the solvent and additive, if necessary. does not check if both sides add to 100.</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="AdditiveConcentration" type="xs:float">
					<xs:annotation>
						<xs:documentation>concentration of additive in mg/ml</xs:documentation>
					</xs:annotation>
				</xs:element>
			</xs:choice>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="RatioType">
		<xs:annotation>
			<xs:documentation>only accepts values between 0-100 iin the form of int:int, user must ensure a valid ratio is input (such as both sides adding to 100)</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:pattern value="(100|[0-9]?[0-9]):(100|[0-9]?[0-9])"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="IntergrationValuesListType">
		<xs:sequence>
			<xs:element name="Baseline" type="IntergrationValuesType"/>
			<xs:element name="Peaks" type="IntergrationValuesType" maxOccurs="unbounded"/>
			<xs:element name="Solvent" type="IntergrationValuesType" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="IntergrationValuesType">
		<xs:attribute name="StartVolume" type="xs:float" use="required"/>
		<xs:attribute name="EndVolume" type="xs:float" use="required"/>
	</xs:complexType>
	<xs:simpleType name="PositiveFloatType">
		<xs:restriction base="xs:float">
			<xs:minInclusive value="0"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== PRDMonash/gpcML/test_pass_XML_file.xml
<?xml version='1.0' encoding='UTF-8'?>
<gpcML xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" Version="TODO" id="0" xsi:noNamespaceSchemaLocation="gpcML.xsd">
  <ContactList>
    <Contact FirstName="Oliver" MiddleName="H" LastName="Cruse" E-mail="ocru0003@student.monash.edu" Institution="Monash University"/>
  </ContactList>
  <Metadata date="2025-10-20" MethodName="C:\_Projects\lily17102025" CalibrationName="C:\_Projects\CAL_Lily_17102025.CAL" Operator="gpc118" InstrumentName="gpc118" RunTime="00:40:00" lastServiceDate="2025-12-01" SampleName="Vial  72: OC_240_PSTY_42h - 1"/>
  <RunTimeData>
    <InstrumentConfiguration>
      <ColumnList>
        <GuardColumn PoreSizeMin="0" PoreSizeMax="0" StationaryPhase="TODO" DateOfInstallation="2025-12-02"/>
        <Column PoreSizeMin="10000" PoreSizeMax="100000" StationaryPhase="styrene-divinylbenzene" DateOfInstallation="2025-12-02"/></ColumnList>
      <OvenList>
        <ColumnOven Temperature="40.000"/>
      </OvenList>
      <Pump FlowRate="1.000"/>
      <Injector InjectionVolume="100.000"/>
      <Eluent>
        <SolventName>THF</SolventName>
        <AdditiveName>LiBr</AdditiveName>
        <RecyclingMode>false</RecyclingMode>
        <AdditiveConcentration>0.8685</AdditiveConcentration>
      </Eluent>
    </InstrumentConfiguration>
    <RawData Compression="false">UmVsYXRpdmUgdGltZSAobWluKSxSSSBzaWduYWwNCjkuNzY5MTcwLC0xLjE2NDA2MA0KOS43ODU4MzAsLTEuMTYzOTgwDQo5LjgwMjUwMCwtMS4xNjM4NTANCjkuODE5MTcwLC0xLjE2MzcwMA0KOS44MzU4MzAsLTEuMTYzNTMwDQo5Ljg1MjUwMCwtMS4xNjMzNDANCjkuODY5MTcwLC0xLjE2MzE5MA0KOS44ODU4MzAsLTEuMTYzMTAwDQo5LjkwMjUwMCwtMS4xNjMwNTANCjkuOTE5MTcwLC0xLjE2MzAyMA0KOS45MzU4MzAsLTEuMTYzMDEwDQo5Ljk1MjUwMCwtMS4xNjI5OTANCjkuOTY5MTcwLC0xLjE2Mjk0MA0KOS45ODU4MzAsLTEuMTYyODYwDQoxMC4wMDI1MDAsLTEuMTYyNzYwDQoxMC4wMTkyMDAsLTEuMTYyNjMwDQoxMC4wMzU4MDAsLTEuMTYyNTAwDQoxMC4wNTI1MDAsLTEuMTYyMzcwDQoxMC4wNjkyMDAsLTEuMTYyMjMwDQoxMC4wODU4MDAsLTEuMTYyMTIwDQoxMC4xMDI1MDAsLTEuMTYyMDUwDQoxMC4xMTkyMDAsLTEuMTYyMDAwDQoxMC4xMzU4MDAsLTEuMTYxOTcwDQoxMC4xNTI1MDAsLTEuMTYxOTcwDQoxMC4xNjkyMDAsLTEuMTYxOTkwDQoxMC4xODU4MDAsLTEuMTYyMDQwDQoxMC4yMDI1MDAsLTEuMTYyMTEwDQoxMC4yMTkyMDAsLTEuMTYyMTgwDQoxMC4yMzU4MDAsLTEuMTYyMjQwDQoxMC4yNTI1MDAsLTEuMTYyMjcwDQoxMC4yNjkyMDAsLTEuMTYyMjcwDQoxMC4yODU4MDAsLTEuMTYyMjIwDQoxMC4zMDI1MDAsLTEuMTYyMTUwDQoxMC4zMTkyMDAsLTEuMTYyMDYwDQoxMC4zMzU4MDAsLTEuMTYxOTcwDQoxMC4zNTI1MDAsLTEuMTYxOTAwDQoxMC4zNjkyMDAsLTEuMTYxODQwDQoxMC4zODU4MDAsLTEuMTYxNzkwDQoxMC40MDI1MDAsLTEuMTYxNzMwDQoxMC40MTkyMDAsLTEuMTYxNjUwDQoxMC40MzU4MDAsLTEuMTYxNTQwDQoxMC40NTI1MDAsLTEuMTYxMzkwDQoxMC40NjkyMDAsLTEuMTYxMjMwDQoxMC40ODU4MDAsLTEuMTYxMDQwDQoxMC41MDI1MDAsLTEuMTYwNzgwDQoxMC41MTkyMDAsLTEuMTYwNTkwDQoxMC41MzU4MDAsLTEuMTYwNDQwDQoxMC41NTI1MDAsLTEuMTYwMzQwDQoxMC41NjkyMDAsLTEuMTYwMjYwDQoxMC41ODU4MDAsLTEuMTYwMjEwDQoxMC42MDI1MDAsLTEuMTYwMTcwDQoxMC42MTkyMDAsLTEuMTYwMTUwDQoxMC42MzU4MDAsLTEuMTYwMTYwDQoxMC42NTI1MDAsLTEuMTYwMTcwDQoxMC42NjkyMDAsLTEuMTYwMTgwDQoxMC42ODU4MDAsLTEuMTYwMjAwDQoxMC43MDI1MDAsLTEuMTYwMjIwDQoxMC43MTkyMDAsLTEuMTYwMjQwDQoxMC43MzU4MDAsLTEuMTYwMjgwDQoxMC43NTI1MDAsLTEuMTYwMzIwDQoxMC43NjkyMDAsLTEuMTYwMzgwDQoxMC43ODU4MDAsLTEuMTYwNDQwDQoxMC44MDI1MDAsLTEuMTYwNTIwDQoxMC44MTkyMDAsLTEuMTYwNjIwDQoxMC44MzU4MDAsLTEuMTYwNjkwDQoxMC44NTI1MDAsLTEuMTYwNzIwDQoxMC44NjkyMDAsLTEuMTYwNzEwDQoxMC44ODU4MDAsLTEuMTYwNjYwDQoxMC45MDI1MDAsLTEuMTYwNTQwDQoxMC45MTkyMDAsLTEuMTYwMzQwDQoxMC45MzU4MDAsLTEuMTYwMTAwDQoxMC45NTI1MDAsLTEuMTU5ODUwDQoxMC45NjkyMDAsLTEuMTU5NjEwDQoxMC45ODU4MDAsLTEuMTU5MzYwDQoxMS4wMDI1MDAsLTEuMTU5MTIwDQoxMS4wMTkyMDAsLTEuMTU4OTEwDQoxMS4wMzU4MDAsLTEuMTU4NzUwDQoxMS4wNTI1MDAsLTEuMTU4NjQwDQoxMS4wNjkyMDAsLTEuMTU4NTgwDQoxMS4wODU4MDAsLTEuMTU4NTYwDQoxMS4xMDI1MDAsLTEuMTU4NTgwDQoxMS4xMTkyMDAsLTEuMTU4NjYwDQoxMS4xMzU4MDAsLTEuMTU4ODAwDQoxMS4xNTI1MDAsLTEuMTU4OTQwDQoxMS4xNjkyMDAsLTEuMTU5MDcwDQoxMS4xODU4MDAsLTEuMTU5MTcwDQoxMS4yMDI1MDAsLTEuMTU5MjMwDQoxMS4yMTkyMDAsLTEuMTU5MjUwDQoxMS4yMzU4MDAsLTEuMTU5MjMwDQoxMS4yNTI1MDAsLTEuMTU5MTcwDQoxMS4yNjkyMDAsLTEuMTU5MDcwDQoxMS4yODU4MDAsLTEuMTU4OTYwDQoxMS4zMDI1MDAsLTEuMTU4ODIwDQoxMS4zMTkyMDAsLTEuMTU4NjYwDQoxMS4zMzU4MDAsLTEuMTU4NDQwDQoxMS4zNTI1MDAsLTEuMTU4MjcwDQoxMS4zNjkyMDAsLTEuMTU4MTQwDQoxMS4zODU4MDAsLTEuMTU4MDYwDQoxMS40MDI1MDAsLTEuMTU4MDQwDQoxMS40MTkyMDAsLTEuMTU4MDYwDQoxMS40MzU4MDAsLTEuMTU4MTMwDQoxMS40NTI1MDAsLTEuMTU4MjIwDQoxMS40NjkyMDAsLTEuMTU4MjcwDQoxMS40ODU4MDAsLTEuMTU4MjgwDQoxMS41MDI1MDAsLTEuMTU4MjQwDQoxMS41MTkyMDAsLTEuMTU4MTYwDQoxMS41MzU4MDAsLTEuMTU4MDUwDQoxMS41NTI1MDAsLTEuMTU3OTAwDQoxMS41NjkyMDAsLTEuMTU3NzgwDQoxMS41ODU4MDAsLTEuMTU3NzEwDQoxMS42MDI1MDAsLTEuMTU3NjgwDQoxMS42MTkyMDAsLTEuMTU3NjkwDQoxMS42MzU4MDAsLTEuMTU3NzEwDQoxMS42NTI1MDAsLTEuMTU3NzMwDQoxMS42NjkyMDAsLTEuMTU3NzQwDQoxMS42ODU4MDAsLTEuMTU3NzIwDQoxMS43MDI1MDAsLTEuMTU3NjcwDQoxMS43MTkyMDAsLTEuMTU3NTgwDQoxMS43MzU4MDAsLTEuMTU3NDcwDQoxMS43NTI1MDAsLTEuMTU3MzMwDQoxMS43NjkyMDAsLTEuMTU3MTIwDQoxMS43ODU4MDAsLTEuMTU2OTMwDQoxMS44MDI1MDAsLTEuMTU2NzQwDQoxMS44MTkyMDAsLTEuMTU2NTYwDQoxMS44MzU4MDAsLTEuMTU2MzkwDQoxMS44NTI1MDAsLTEuMTU2MjIwDQoxMS44NjkyMDAsLTEuMTU2MDQwDQoxMS44ODU4MDAsLTEuMTU1ODgwDQoxMS45MDI1MDAsLTEuMTU1NzUwDQoxMS45MTkyMDAsLTEuMTU1NjMwDQoxMS45MzU4MDAsLTEuMTU1NTIwDQoxMS45NTI1MDAsLTEuMTU1NDEwDQoxMS45NjkyMDAsLTEuMTU1MjkwDQoxMS45ODU4MDAsLTEuMTU1MTkwDQoxMi4wMDI1MDAsLTEuMTU1MTMwDQoxMi4wMTkyMDAsLTEuMTU1MDkwDQoxMi4wMzU4MDAsLTEuMTU1MDYwDQoxMi4wNTI1MDAsLTEuMTU1MDQwDQoxMi4wNjkyMDAsLTEuMTU1MDEwDQoxMi4wODU4MDAsLTEuMTU0OTcwDQoxMi4xMDI1MDAsLTEuMTU0OTMwDQoxMi4xMTkyMDAsLTEuMTU0OTAwDQoxMi4xMzU4MDAsLTEuMTU0ODkwDQoxMi4xNTI1MDAsLTEuMTU0OTAwDQoxMi4xNjkyMDAsLTEuMTU0OTYwDQoxMi4xODU4MDAsLTEuMTU1MDUwDQoxMi4yMDI1MDAsLTEuMTU1MTMwDQoxMi4yMTkyMDAsLTEuMTU1MTcwDQoxMi4yMzU4MDAsLTEuMTU1MTYwDQoxMi4yNTI1MDAsLTEuMTU1MDkwDQoxMi4yNjkyMDAsLTEuMTU0OTcwDQoxMi4yODU4MDAsLTEuMTU0NzkwDQoxMi4zMDI1MDAsLTEuMTU0NTMwDQoxMi4zMTkyMDAsLTEuMTU0MzMwDQoxMi4zMzU4MDAsLTEuMTU0MTkwDQoxMi4zNTI1MDAsLTEuMTU0MTEwDQoxMi4zNjkyMDAsLTEuMTU0MDkwDQoxMi4zODU4MDAsLTEuMTU0MTIwDQoxMi40MDI1MDAsLTEuMTU0MTcwDQoxMi40MTkyMDAsLTEuMTU0MTkwDQoxMi40MzU4MDAsLTEuMTU0MTYwDQoxMi40NTI1MDAsLTEuMTU0MDgwDQoxMi40NjkyMDAsLTEuMTUzOTcwDQoxMi40ODU4MDAsLTEuMTUzODIwDQoxMi41MDI1MDAsLTEuMTUzNjQwDQoxMi41MTkyMDAsLTEuMTUzNTIwDQoxMi41MzU4MDAsLTEuMTUzNDQwDQoxMi41NTI1MDAsLTEuMTUzMzgwDQoxMi41NjkyMDAsLTEuMTUzMzMwDQoxMi41ODU4MDAsLTEuMTUzMjUwDQoxMi42MDI1MDAsLTEuMTUzMTEwDQoxMi42MTkyMDAsLTEuMTUyODcwDQoxMi42MzU4MDAsLTEuMTUyNjAwDQoxMi42NTI1MDAsLTEuMTUyMzEwDQoxMi42NjkyMDAsLTEuMTUyMDIwDQoxMi42ODU4MDAsLTEuMTUxNzcwDQoxMi43MDI1MDAsLTEuMTUxNTUwDQoxMi43MTkyMDAsLTEuMTUxMzcwDQoxMi43MzU4MDAsLTEuMTUxMjgwDQoxMi43NTI1MDAsLTEuMTUxMjYwDQoxMi43NjkyMDAsLTEuMTUxMjcwDQoxMi43ODU4MDAsLTEuMTUxMzAwDQoxMi44MDI1MDAsLTEuMTUxMzMwDQoxMi44MTkyMDAsLTEuMTUxMzYwDQoxMi44MzU4MDAsLTEuMTUxMzgwDQoxMi44NTI1MDAsLTEuMTUxMzcwDQoxMi44NjkyMDAsLTEuMTUxMzQwDQoxMi44ODU4MDAsLTEuMTUxMjkwDQoxMi45MDI1MDAsLTEuMTUxMjQwDQoxMi45MTkyMDAsLTEuMTUxMTgwDQoxMi45MzU4MDAsLTEuMTUxMTMwDQoxMi45NTI1MDAsLTEuMTUxMTIwDQoxMi45NjkyMDAsLTEuMTUxMTUwDQoxMi45ODU4MDAsLTEuMTUxMjIwDQoxMy4wMDI1MDAsLTEuMTUxMzEwDQoxMy4wMTkyMDAsLTEuMTUxNDIwDQoxMy4wMzU4MDAsLTEuMTUxNTYwDQoxMy4wNTI1MDAsLTEuMTUxNjUwDQoxMy4wNjkyMDAsLTEuMTUxNzEwDQoxMy4wODU4MDAsLTEuMTUxNzIwDQoxMy4xMDI1MDAsLTEuMTUxNzAwDQoxMy4xMTkyMDAsLTEuMTUxNjUwDQoxMy4xMzU4MDAsLTEuMTUxNTcwDQoxMy4xNTI1MDAsLTEuMTUxNTAwDQoxMy4xNjkyMDAsLTEuMTUxNDQwDQoxMy4xODU4MDAsLTEuMTUxMzkwDQoxMy4yMDI1MDAsLTEuMTUxMzYwDQoxMy4yMTkyMDAsLTEuMTUxMzQwDQoxMy4yMzU4MDAsLTEuMTUxMzEwDQoxMy4yNTI1MDAsLTEuMTUxMjcwDQoxMy4yNjkyMDAsLTEuMTUxMjAwDQoxMy4yODU4MDAsLTEuMTUxMTAwDQoxMy4zMDI1MDAsLTEuMTUwOTgwDQoxMy4zMTkyMDAsLTEuMTUwODQwDQoxMy4zMzU4MDAsLTEuMTUwNjgwDQoxMy4zNTI1MDAsLTEuMTUwNTAwDQoxMy4zNjkyMDAsLTEuMTUwMzUwDQoxMy4zODU4MDAsLTEuMTUwMjIwDQoxMy40MDI1MDAsLTEuMTUwMTEwDQoxMy40MTkyMDAsLTEuMTUwMDEwDQoxMy40MzU4MDAsLTEuMTQ5ODgwDQoxMy40NTI1MDAsLTEuMTQ5NzQwDQoxMy40NjkyMDAsLTEuMTQ5NjAwDQoxMy40ODU4MDAsLTEuMTQ5NDUwDQoxMy41MDI1MDAsLTEuMTQ5MzEwDQoxMy41MTkyMDAsLTEuMTQ5MTgwDQoxMy41MzU4MDAsLTEuMTQ5MDcwDQoxMy41NTI1MDAsLTEuMTQ4OTkwDQoxMy41NjkyMDAsLTEuMTQ4OTUwDQoxMy41ODU4MDAsLTEuMTQ4OTkwDQoxMy42MDI1MDAsLTEuMTQ5MDgwDQoxMy42MTkyMDAsLTEuMTQ5MjQwDQoxMy42MzU4MDAsLTEuMTQ5NDMwDQoxMy42NTI1MDAsLTEuMTQ5NjcwDQoxMy42NjkyMDAsLTEuMTQ5OTkwDQoxMy42ODU4MDAsLTEuMTUwMjgwDQoxMy43MDI1MDAsLTEuMTUwNTMwDQoxMy43MTkyMDAsLTEuMTUwNzYwDQoxMy43MzU4MDAsLTEuMTUwOTcwDQoxMy43NTI1MDAsLTEuMTUxMTQwDQoxMy43NjkyMDAsLTEuMTUxMzIwDQoxMy43ODU4MDAsLTEuMTUxNDQwDQoxMy44MDI1MDAsLTEuMTUxNTAwDQoxMy44MTkyMDAsLTEuMTUxNTEwDQoxMy44MzU4MDAsLTEuMTUxNDcwDQoxMy44NTI1MDAsLTEuMTUxNDAwDQoxMy44NjkyMDAsLTEuMTUxMjkwDQoxMy44ODU4MDAsLTEuMTUxMTYwDQoxMy45MDI1MDAsLTEuMTUxMDgwDQoxMy45MTkyMDAsLTEuMTUxMDMwDQoxMy45MzU4MDAsLTEuMTUxMDIwDQoxMy45NTI1MDAsLTEuMTUxMDQwDQoxMy45NjkyMDAsLTEuMTUxMTAwDQoxMy45ODU4MDAsLTEuMTUxMTcwDQoxNC4wMDI1MDAsLTEuMTUxMjIwDQoxNC4wMTkyMDAsLTEuMTUxMjUwDQoxNC4wMzU4MDAsLTEuMTUxMjQwDQoxNC4wNTI1MDAsLTEuMTUxMjEwDQoxNC4wNjkyMDAsLTEuMTUxMTQwDQoxNC4wODU4MDAsLTEuMTUxMDMwDQoxNC4xMDI1MDAsLTEuMTUwODYwDQoxNC4xMTkyMDAsLTEuMTUwNzAwDQoxNC4xMzU4MDAsLTEuMTUwNTcwDQoxNC4xNTI1MDAsLTEuMTUwNDQwDQoxNC4xNjkyMDAsLTEuMTUwMzUwDQoxNC4xODU4MDAsLTEuMTUwMzAwDQoxNC4yMDI1MDAsLTEuMTUwMjkwDQoxNC4yMTkyMDAsLTEuMTUwMzEwDQoxNC4yMzU4MDAsLTEuMTUwMzQwDQoxNC4yNTI1MDAsLTEuMTUwMzcwDQoxNC4yNjkyMDAsLTEuMTUwMzgwDQoxNC4yODU4MDAsLTEuMTUwMzYwDQoxNC4zMDI1MDAsLTEuMTUwMjkwDQoxNC4zMTkyMDAsLTEuMTUwMTgwDQoxNC4zMzU4MDAsLTEuMTUwMDQwDQoxNC4zNTI1MDAsLTEuMTQ5ODgwDQoxNC4zNjkyMDAsLTEuMTQ5NzEwDQoxNC4zODU4MDAsLTEuMTQ5NTQwDQoxNC40MDI1MDAsLTEuMTQ5MzYwDQoxNC40MTkyMDAsLTEuMTQ5MTcwDQoxNC40MzU4MDAsLTEuMTQ5MDQwDQoxNC40NTI1MDAsLTEuMTQ4OTQwDQoxNC40NjkyMDAsLTEuMTQ4ODcwDQoxNC40ODU4MDAsLTEuMTQ4ODAwDQoxNC41MDI1MDAsLTEuMTQ4NzQwDQoxNC41MTkyMDAsLTEuMTQ4NjYwDQoxNC41MzU4MDAsLTEuMTQ4NTcwDQoxNC41NTI1MDAsLTEuMTQ4NDkwDQoxNC41NjkyMDAsLTEuMTQ4NDAwDQoxNC41ODU4MDAsLTEuMTQ4MzMwDQoxNC42MDI1MDAsLTEuMTQ4MjUwDQoxNC42MTkyMDAsLTEuMTQ4MTcwDQoxNC42MzU4MDAsLTEuMTQ4MTAwDQoxNC42NTI1MDAsLTEuMTQ4MDIwDQoxNC42NjkyMDAsLTEuMTQ3OTMwDQoxNC42ODU4MDAsLTEuMTQ3ODUwDQoxNC43MDI1MDAsLTEuMTQ3NzYwDQoxNC43MTkyMDAsLTEuMTQ3NjcwDQoxNC43MzU4MDAsLTEuMTQ3NjAwDQoxNC43NTI1MDAsLTEuMTQ3NTUwDQoxNC43NjkyMDAsLTEuMTQ3NTEwDQoxNC43ODU4MDAsLTEuMTQ3NDYwDQoxNC44MDI1MDAsLTEuMTQ3NDEwDQoxNC44MTkyMDAsLTEuMTQ3MzMwDQoxNC44MzU4MDAsLTEuMTQ3MjAwDQoxNC44NTI1MDAsLTEuMTQ3MDgwDQoxNC44NjkyMDAsLTEuMTQ2OTUwDQoxNC44ODU4MDAsLTEuMTQ2ODIwDQoxNC45MD
